# Generated by Django 4.1.3 on 2022-11-30 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0021_widhdraw_requests_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widhdraw_requests',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='widhdraw_requests',
            name='status',
        ),
        migrations.RemoveField(
            model_name='widhdraw_requests',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='widhdraw_requests',
            name='trans_detail',
        ),
        migrations.RemoveField(
            model_name='widhdraw_requests',
            name='userid',
        ),
        migrations.AddField(
            model_name='widhdraw_requests',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='widhdraw_requests',
            name='wallet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='widhdraw_requests',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='widhdraw_requests',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='widhdraw_requests',
            name='type',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
