# Generated by Django 4.1.3 on 2022-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0022_remove_widhdraw_requests_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widhdraw_requests',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
