# Generated by Django 4.1.3 on 2022-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0023_widhdraw_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widhdraw_requests',
            name='type',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
