# Generated by Django 4.1.3 on 2022-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0024_alter_widhdraw_requests_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlotteriesthreem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
