# Generated by Django 4.1.3 on 2022-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0025_alter_newlotteriesthreem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlotteries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newlotteriesnine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
