# Generated by Django 4.1.3 on 2022-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0027_buychips'),
    ]

    operations = [
        migrations.AddField(
            model_name='buychips',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
