# Generated by Django 4.1.3 on 2022-12-03 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0028_buychips_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('fromusername', models.CharField(max_length=50, null=True, unique=True)),
                ('tousername', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
